### ISSUE TITLE
Support chain-able ElseIf statements

### ISSUE THREAD

**Issue by Snarr** [littlehorse-enterprises/littlehorse#1453]
We should support chain-able `ElseIf` statements in the SDK to create a better user experience for chaining conditionals.

## Proposal

```java
wf.doIf(foo, body -> { body.execute("my-task-a"); })
    .addIfElse(1, body -> { body.execute("my-task-b"); })
    .addIfElse(2, body -> { body.execute("my-task-c"); })
    .addElse(body -> { body.execute("my-task"); });
```

This greatly improves upon the existing functionality for chaining If Statements, which relies on nesting If Statements inside of one another.

## SDK Support

- [x] Python - #1463 
- [x] Java - #1492 
- [x] Go - #1491
- [x] C# - #1475 

## Documentation

- [x] Are all documentation references for this feature up to date? https://github.com/littlehorse-enterprises/lh-site/pull/192
- [x] Are all examples that use this feature up to date? https://github.com/littlehorse-enterprises/littlehorse/pull/1518/files

**Comment by Snarr** [comment]
How the new If/Else functionality works in the SDK:

wf.doIf(condition, body) psuedocode:

```
1. Add NOP node #1 to thread
2. Add body to thread 
 - Adds outgoing edge from NOP #1 to first node of body with condition #1
3. Add NOP node #2 to thread
4. Add outgoing edge from last node of body to NOP node #2
```

So the following WfSpec will generate the following structure:

```java
wf -> {
  wf.doIf(condition, body -> { body.execute("task-a"); });
}
```

```
threadSpecs.entrypoint.nodes:
- 0-entrypoint-ENTRYPOINT
  - outgoingEdge: 1-nop-NOP
- 1-nop-NOP
  - outgoingEdge: 2-task-a-TASK with condition
- 2-task-a-TASK
  - outgoingEdge: 3-nop-NOP
- 3-nop-NOP
  - outgoingEdge: 4-exit-EXIT
- 4-exit-EXIT
```



Subsequent method calls to 'elseIf' will use a 'cut and cover' technique where they insert the elseIf bodies and conditions and connect them to the final NOP node retroactively.
